collections:
  projects:
    output: true

# Enable LiveReload
livereload: true

# Site settings
title: Brittany Woodard
description: 
url: "https://www.brittanywoodard.com"  
baseurl: ""  # leave empty if site is served at domain root
lang: en
timezone: America/New_York

author:
  name: Brittany Woodard
  url: "https://www.brittanywoodard.com"

logo: "/uploads/brittany-woodard-card.png"
social:
  name: Brittany Woodard
  links:
    - https://www.instagram.com/{{ site.site-settings.social.instagram_username }}
    - https://www.linkedin.com/{{ site.site-settings.social.linkedin_username }}

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

